config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'books#index'
    # get 'books/reserve_list' => 'books#reserve_list'
    get 'books/outtime_list' => 'books#outtime_list'
    # get 'books/restitution_list' => 'books#restitution_list'
    get 'books/honor_list' => 'books#honor_list'
    # patch 'books/reserve/:id' => 'books#reserve', as: :book_reserve
    # patch 'books/restitution/:id' => 'books#restitution', as: :book_rest
    match 'books/restitution_list', to: 'books#restitution_list', via: 'get', as: :book_restitutionlist
    match 'books/reserve_list', to: 'books#reserve_list', via: 'get', as: :book_reservelist
    match 'books/reserve/:id', to: 'books#reserve', via: 'post', as: :book_reserve
    match 'books/restitution/:id', to: 'books#restitution', via: 'post', as: :book_rest

    resources :activities
    resources :tags
    resources :evaluations
    resources :donors
    resources :books
    resources :users
  end

  match '/donors/search', to: 'donors#search', via: 'post'
  match '/donors/donor/:book_id', to: 'donors#donor', via: 'get'
  match '/books/reserve/:id', to: 'books#reserve', via: 'get', as: :book_reserve
  match '/books/restitution/:id', to: 'books#restitution', via: 'get', as: :book_rest
  match '/users/borrow/:id', to: 'users#borrow', via: 'get', as: :borrow
  
  root 'books#index'
  resources :books
  resources :users
  resources :activities
  resources :donors
end

app/models/book.rb
class Book
  include Mongoid::Document
  Mongoid.raise_not_found_error = false

  field :name, type: String
  field :author, type: String
  field :summary, type: String
  # field :tag, type: String
  # field :donor, type: String
  field :image, type: String
  field :large_image, type: String
  field :donate_time, type: DateTime
  field :status, type: String
  field :borrow_time, type: DateTime
  field :shoud_restitution_time, type: DateTime
  field :actual_restitution_time, type: DateTime
  field :barcode, type: String
  field :borrow_times, type: String
  field :reserve_user_id, type: String

  validates :name, presence: true
  validates :author, presence: true
  # validates :donor, presence: true
  validates :barcode, presence: true

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :borrowers, class_name: 'User', inverse_of: :borrowed_books
  belongs_to :reserver, class_name: 'User', inverse_of: :reserved_books
  has_one :current_borrowed_user, class_name: 'User', inverse_of: :current_borrow_book
  has_many :evaluations
  belongs_to :donor

  def current_borrower
    if self.status == 'BORROWED'
      return self.borrowers.last
    else
      return false
    end
  end

  def confirmborrow
    if self.status == "RESERVERD"
      self.status = "BORROWED"
      self.borrowers << self.reserver
      self.reserver.borrowed_books << self
      self.reserver.save
      self.save
      self.reserver = nil
      return true
    end
    return false
  end

  def confimrestitu
    if self.status == "RESTITUTIONED"
      self.status = "CANBORROW"
      self.save
      return true
    end
    return false
  end

  def get_info_from_douban
    res = Net::HTTP.get(URI.parse("https://api.douban.com/v2/book/isbn/#{self.barcode}"))
    json_info = JSON::parse(res)
    self.name = json_info['subtitle']
    self.author = json_info['author'][0]
    self.image = json_info['image']
    self.summary = json_info['summary']
    self.large_image = json_info['images']['large']
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :reserve, :restitution]
  layout 'admin'
  
  # GET /books
  # GET /books.json
  def index
    #@books = Book.all
    @books = Book.page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @books, status: :ok }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.status = "CANBORROW"
    @book.get_info_from_douban

    respond_to do |format|
      if @book.save
        format.html { redirect_to admin_book_url(@book), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/reserve/1
  # PATCH/PUT /books/reserve/1.json
  def reserve
    reserver = User.find(params['user_id'])

    if reserver.nil?
      error = "参数错误，用户不存在!"
      is_success = false
    elsif params['command'] == "RESERVE"
      respond_to do |format|
        if reserver.reseve(@book)
          format.json { render :json => "预约成功", status: :ok }
        else
          format.json { render :json => "书籍被预约或借出，请稍候再尝试预约！", status: :error }
        end
      end
    elsif params['command'] == "CANCELRESERVE"
      respond_to do |format|
        if reserver.cancel_reseve(@book)
          format.json { render :json => "取消预约成功", status: :ok }
        else
          format.json { render :json => "取消预约失败，请稍候尝试", status: :error }
        end
      end
    else
      respond_to do |format|
        format.json { render :json => "参数错误", status: :error }
      end
    end
  end

  def restitution
    restitutioner = User.find(params['user_id'])

    if restitutioner.nil?
      error = "参数错误，用户不存在!"
      is_success = false
    else
      respond_to do |format|
        if restitutioner.restitution(@book)
          format.json { render :json => "归还预约成功，等待管理员处理", status: :ok }
        else
          format.json { render :json => "归还失败，请稍候尝试", status: :error }
        end
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    # respond_to do |format|
    #   if @book.update(book_params)
    #     format.html { redirect_to @book, notice: 'Book was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @book }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @book.errors, status: :unprocessable_entity }
    #   end
    # end
    if params['book']['command'] == 'CONFIRMBORROW'
      respond_to do |format|
        if @book.confirmborrow
          format.html { redirect_to '/admin/books/reserve_list' }
        else
          format.html { render :reserve_list }
        end
      end
    elsif params['book']['command'] == 'CONFIRMRESTITUTE'
      respond_to do |format|
        if @book.confimrestitu
          format.html { redirect_to '/admin/books/restitution_list'}
        else
          format.html { render :restitution_list }
        end
      end
    else
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to admin_books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reserve_list
    @books = Book.where(:status => "RESERVERD").page(params[:page]).per(1)
  end

  def restitution_list
    @books = Book.where(:status => "RESTITUTIONED").page(params[:page]).per(1)
  end

  def outtime_list
    @books = Book.page(params[:page]).per(1)
  end

  def honor_list
    @books = Book.page(params[:page]).per(1)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:donate_time,
                                   :barcode)
    end

    # def response(error)
      
    # end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :reserve, :restitution]

  # GET /books
  # GET /books.json
  def index
    # @books = Book.all
    @books = Book.page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @books, status: :ok }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.status = "CANBORROW"

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/reserve/1
  # PATCH/PUT /books/reserve/1.json
  def reserve
    reserver = User.find(current_user._id)

    if reserver.nil?
      error = "请登录后再操作!"
      is_success = false
    elsif params['command'] == "RESERVE"
      respond_to do |format|
        if reserver.reseve(@book)
          # format.json { render :json => "预约成功", status: :ok }
          format.js
          #redirect_to @book
        else
          format.json { render :json => "书籍被预约或借出，请稍候再尝试预约！", status: :error }
        end
      end
    elsif params['command'] == "CANCELRESERVE"
      respond_to do |format|
        if reserver.cancel_reseve(@book)
          format.js
          # format.json { render :json => "取消预约成功", status: :ok }
        else
          format.json { render :json => "取消预约失败，请稍候尝试", status: :error }
        end
      end
    else
      respond_to do |format|
        format.json { render :json => "参数错误", status: :error }
      end
    end
  end

  def restitution
    restitutioner = User.find(current_user._id)

    if restitutioner.nil?
      error = "参数错误，用户不存在!"
      is_success = false
    else
      respond_to do |format|
        if restitutioner.restitution(@book)
          # format.json { render :json => "归还预约成功，等待管理员处理", status: :ok }
          format.js
        else
          format.json { render :json => "归还失败，请稍候尝试", status: :error }
        end
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
    # if params['book']['command'] == 'CONFIRMBORROW'
    #   respond_to do |format|
    #     if @book.confirmborrow
    #       format.html { redirect_to @book, notice: '确认借出成功' }
    #     else
    #       format.html { render :reserve_list }
    #     end
    #   end
    # elsif params['book']['command'] == 'CONFIRMRESTITUTE'
    #   respond_to do |format|
    #     if @book.confimrestitu
    #       format.html { redirect_to @book, notice: '确认归还成功' }
    #     else
    #       format.html { render :restitution_list }
    #     end
    #   end
    # else
    # end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reserve_list
    @books = Book.where(:status => "RESERVERD").page(params[:page]).per(1)
  end

  def restitution_list
    @books = Book.where(:status => "RESTITUTIONED").page(params[:page]).per(1)
  end

  def outtime_list
    @books = Book.page(params[:page]).per(1)
  end

  def honor_list
    @books = Book.page(params[:page]).per(1)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, 
                                   :author, 
                                   :tags,
                                   :donate_time,
                                   :barcode)
    end

    # def response(error)
      
    # end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/_error.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book] do |f| %>
  <%= render 'error' %>
  <!-- <div class="form-group">
    <%#= f.label :name , :value => "书籍名称:"%><br>
    <%#= f.text_field :name, :class => "form-control", :placeholder => "输入书名" %>
  </div>

  <div class="form-group">
    <%#= f.label :author, :value => "作者：" %><br>
    <%#= f.text_field :author, :class => "form-control", :placeholder => "输入作者" %>
  </div>

  <div class="form-group">
    <%#= f.label :tags, :value => "标签：" %>
    <%#= f.text_field :tags, :class => "form-control",:placeholder => "输入标签" %>
  </div>

  <div class="form-group">
    <%#= f.label :donor, :value => "捐赠者：" %>
    <%#= f.text_field :donor, :class => "form-control",:placeholder => "输入捐赠者姓名" %>
  </div>
 -->
  <div class="form-group">
    <%= f.label :donate_time, :value => "捐赠时间：" %>
    <%= f.date_field :donate_time, :class => "form-control",:placeholder => "输入捐赠时间" %>
  </div>
  <div class="form-group">
    <%= f.label :barcode, :value => "条形码：" %>
    <%= f.text_field :barcode, :class => "form-control", :placeholder => "条形码" %>
  </div>

  <div class="form-group">
    <%= f.submit :class => "btn btn-success btn-block", :value => "添加书籍" %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_book_path(@book) %> |
<%= link_to 'Back', admin_books_path %>

app/views/admin/books/honor_list.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <i class="fa fa-list-ul"></i> 预约书籍列表
    </h1>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-book"></i> 书籍管理
      </li>
      <li class="active">
          <i class="fa fa-list-ul"></i> 预约书籍列表
      </li>
    </ol>
  </div>
</div>

<br>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>书名</th>
            <th>作者</th>
            <th>捐赠者</th>
            <th>捐赠时间</th>
            <th>当前状态</th>
            <th>借阅者</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
              <td><%= book.name %></td>
              <td><%= book.author %></td>
              <td><%= book.donor %></td>
              <td><%= book.donate_time.to_formatted_s(:db) %></td>
              <td>
                <% if book.status == "BORROWED" %>
                  <span style="color:red;"> 已借出 </span>
                <% elsif book.status == "CANBORROW" %>
                  可&nbsp;&nbsp;&nbsp;&nbsp;借
                <% end %>
              </td>
              <td>
                <% if book.current_borrower %>
                  <%= link_to book.current_borrower.true_name , book.current_borrower%>
                <% else %>
                  无
                <% end %>
              </td>
              <td><%= link_to '查看书籍', admin_book_path(book) , :class => 'btn btn-success btn-sm'%> &nbsp;
                  <%= link_to '编辑书籍', edit_admin_book_path(book), :class => 'btn btn-primary btn-sm' %> &nbsp;
                  <%= link_to '删除书籍', admin_book_path(book), method: :delete, data: { confirm: '确认删除？' }, :class=>'btn btn-danger btn-sm'%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= paginate @books, :outer_window => 2 %>

app/views/admin/books/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <i class="fa fa-list-ul"></i> 书籍列表
    </h1>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-book"></i> 书籍管理
      </li>
      <li class="active">
          <i class="fa fa-list-ul"></i> 书籍列表
      </li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-lg-12 cs-add-book-btn">
    <%= link_to '添加书籍', new_admin_book_path , :class => 'btn btn-success btn-sm pull-right'%>
  </div>
</div>
<br>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>书名</th>
            <th>作者</th>
            <th>捐赠者</th>
            <th>捐赠时间</th>
            <th>当前状态</th>
            <th>借阅者</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
              <td><%= book.name %></td>
              <td><%= book.author %></td>
              <td><%= book.donor %></td>
              <td><%= book.donate_time.to_formatted_s(:db) %></td>
              <td>
                <% if book.status == "BORROWED" %>
                  <span style="color:red;"> 已借出 </span>
                <% elsif book.status == "CANBORROW" %>
                  可&nbsp;&nbsp;&nbsp;&nbsp;借
                <% end %>
              </td>
              <td>
                <% if book.current_borrower %>
                  <%= link_to book.current_borrower.true_name , book.current_borrower%>
                <% else %>
                  无
                <% end %>
              </td>
              <td><%= link_to '查看书籍', admin_book_path(book) , :class => 'btn btn-success btn-sm'%> &nbsp;
                  <%= link_to '编辑书籍', edit_admin_book_path(book), :class => 'btn btn-primary btn-sm' %> &nbsp;
                  <%= link_to '删除书籍', admin_book_path(book), method: :delete, data: { confirm: '确认删除？' }, :class=>'btn btn-danger btn-sm'%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= paginate @books, :outer_window => 2 %>

app/views/admin/books/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <i class="fa fa-plus"></i> 添加书籍
    </h1>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-fw fa-connectdevelop"></i> 书籍管理
      </li>
      <li class="active">
          <i class="fa fa-plus"></i> 添加书籍
      </li>
    </ol>
  </div>
</div>

<div class="row">
  <%= render 'form' %>
</div>

app/views/admin/books/outtime_list.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <i class="fa fa-list-ul"></i> 超期书籍列表
    </h1>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-book"></i> 书籍管理
      </li>
      <li class="active">
          <i class="fa fa-list-ul"></i> 超期书籍列表
      </li>
    </ol>
  </div>
</div>

<br>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>书名</th>
            <th>作者</th>
            <th>捐赠者</th>
            <th>捐赠时间</th>
            <th>当前状态</th>
            <th>借阅者</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
              <td><%= book.name %></td>
              <td><%= book.author %></td>
              <td><%= book.donor %></td>
              <td><%= book.donate_time.to_formatted_s(:db) %></td>
              <td>
                <% if book.status == "BORROWED" %>
                  <span style="color:red;"> 已借出 </span>
                <% elsif book.status == "CANBORROW" %>
                  可&nbsp;&nbsp;&nbsp;&nbsp;借
                <% end %>
              </td>
              <td>
                <% if book.current_borrower %>
                  <%= link_to book.current_borrower.true_name , book.current_borrower%>
                <% else %>
                  无
                <% end %>
              </td>
              <td><%= link_to '查看书籍', admin_book_path(book) , :class => 'btn btn-success btn-sm'%> &nbsp;
                  <%= link_to '编辑书籍', edit_admin_book_path(book), :class => 'btn btn-primary btn-sm' %> &nbsp;
                  <%= link_to '删除书籍', admin_book_path(book), method: :delete, data: { confirm: '确认删除？' }, :class=>'btn btn-danger btn-sm'%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= paginate @books, :outer_window => 2 %>

app/views/admin/books/reserve_list.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <i class="fa fa-list-ul"></i> 预约书籍列表
    </h1>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-book"></i> 书籍管理
      </li>
      <li class="active">
          <i class="fa fa-list-ul"></i> 预约书籍列表
      </li>
    </ol>
  </div>
</div>

<br>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>书名</th>
            <th>作者</th>
            <th>捐赠者</th>
            <th>预约者</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
              <td><%= link_to book.name, book %></td>
              <td><%= book.author %></td>
              <td><%= book.donor %></td>
              <td><%= link_to book.reserver.true_name, book.reserver %></td>
              <td>
                <%= form_for [:admin, book] do |f| %>
                  <%= f.hidden_field :command, value: "CONFIRMBORROW"%>
                  <%= f.submit "确认借出", class: "btn btn-danger btn-sm" %>
                <% end %>
              </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= paginate @books, :outer_window => 2 %>

app/views/admin/books/restitution_list.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <i class="fa fa-list-ul"></i> 归还书籍列表
    </h1>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-book"></i> 书籍管理
      </li>
      <li class="active">
          <i class="fa fa-list-ul"></i> 归还书籍列表
      </li>
    </ol>
  </div>
</div>

<br>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>书名</th>
            <th>作者</th>
            <th>捐赠者</th>
            <th>借阅者</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
              <td><%= book.name %></td>
              <td><%= book.author %></td>
              <td><%= book.donor %></td>
              <td>
                <% if book.current_borrower %>
                  <%= link_to book.current_borrower.true_name , book.current_borrower%>
                <% else %>
                  无
                <% end %>
              </td>
              <td>
                <%= form_for [:admin, book] do |f| %>
                  <%= f.hidden_field :command, value: "CONFIRMRESTITUTE"%>
                  <%= f.submit "确认归还", class: "btn btn-danger btn-sm" %>
                <% end %>
              </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= paginate @books, :outer_window => 2 %>

app/views/admin/books/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <img src="<%= @book.image %>" alt="">
    <h2><%= @book.name %></h2>
    <p><%= @book.author %></p>
    <p><%= @book.summary %></p>
  </div>
</div>
<%#= link_to 'Edit', edit_admin_book_path(@book) %>
<%#= link_to 'Back', admin_books_path %>