config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'books#index'
    # get 'books/reserve_list' => 'books#reserve_list'
    get 'books/outtime_list' => 'books#outtime_list'
    # get 'books/restitution_list' => 'books#restitution_list'
    get 'books/honor_list' => 'books#honor_list'
    # patch 'books/reserve/:id' => 'books#reserve', as: :book_reserve
    # patch 'books/restitution/:id' => 'books#restitution', as: :book_rest
    match 'books/restitution_list', to: 'books#restitution_list', via: 'get', as: :book_restitutionlist
    match 'books/reserve_list', to: 'books#reserve_list', via: 'get', as: :book_reservelist
    match 'books/reserve/:id', to: 'books#reserve', via: 'post', as: :book_reserve
    match 'books/restitution/:id', to: 'books#restitution', via: 'post', as: :book_rest

    resources :activities
    resources :tags
    resources :evaluations
    resources :donors
    resources :books
    resources :users
  end

  match '/donors/search', to: 'donors#search', via: 'post'
  match '/donors/donor/:book_id', to: 'donors#donor', via: 'get'
  match '/books/reserve/:id', to: 'books#reserve', via: 'get', as: :book_reserve
  match '/books/restitution/:id', to: 'books#restitution', via: 'get', as: :book_rest
  match '/users/borrow/:id', to: 'users#borrow', via: 'get', as: :borrow
  
  root 'books#index'
  resources :books
  resources :users
  resources :activities
  resources :donors
end

app/models/evaluation.rb
class Evaluation
  include Mongoid::Document

  field :content, type: String
  field :time, type: String

  validates :content, presence: true
  validates :time, presence: true

  belongs_to :book
  belongs_to :user
end

app/controllers/admin/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: [:show, :edit, :update, :destroy]

  # GET /evaluations
  # GET /evaluations.json
  def index
    @evaluations = Evaluation.all
  end

  # GET /evaluations/1
  # GET /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations
  # POST /evaluations.json
  def create
    @evaluation = Evaluation.new(evaluation_params)

    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully created.' }
        format.json { render :show, status: :created, location: @evaluation }
      else
        format.html { render :new }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1
  # PATCH/PUT /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluation }
      else
        format.html { render :edit }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    @evaluation.destroy
    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: 'Evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_params
      params[:evaluation]
    end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/admin/evaluations/_form.html.erb
<%= form_for(@evaluation) do |f| %>
  <% if @evaluation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluation.errors.count, "error") %> prohibited this evaluation from being saved:</h2>

      <ul>
      <% @evaluation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/evaluations/edit.html.erb
<h1>Editing Evaluation</h1>

<%= render 'form' %>

<%= link_to 'Show', @evaluation %> |
<%= link_to 'Back', evaluations_path %>

app/views/admin/evaluations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Evaluations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
      <tr>
        <td><%= link_to 'Show', evaluation %></td>
        <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
        <td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluation', new_evaluation_path %>

app/views/admin/evaluations/new.html.erb
<h1>New Evaluation</h1>

<%= render 'form' %>

<%= link_to 'Back', evaluations_path %>

app/views/admin/evaluations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_evaluation_path(@evaluation) %> |
<%= link_to 'Back', evaluations_path %>