config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'books#index'
    # get 'books/reserve_list' => 'books#reserve_list'
    get 'books/outtime_list' => 'books#outtime_list'
    # get 'books/restitution_list' => 'books#restitution_list'
    get 'books/honor_list' => 'books#honor_list'
    # patch 'books/reserve/:id' => 'books#reserve', as: :book_reserve
    # patch 'books/restitution/:id' => 'books#restitution', as: :book_rest
    match 'books/restitution_list', to: 'books#restitution_list', via: 'get', as: :book_restitutionlist
    match 'books/reserve_list', to: 'books#reserve_list', via: 'get', as: :book_reservelist
    match 'books/reserve/:id', to: 'books#reserve', via: 'post', as: :book_reserve
    match 'books/restitution/:id', to: 'books#restitution', via: 'post', as: :book_rest

    resources :activities
    resources :tags
    resources :evaluations
    resources :donors
    resources :books
    resources :users
  end

  match '/donors/search', to: 'donors#search', via: 'post'
  match '/donors/donor/:book_id', to: 'donors#donor', via: 'get'
  match '/books/reserve/:id', to: 'books#reserve', via: 'get', as: :book_reserve
  match '/books/restitution/:id', to: 'books#restitution', via: 'get', as: :book_rest
  match '/users/borrow/:id', to: 'users#borrow', via: 'get', as: :borrow
  
  root 'books#index'
  resources :books
  resources :users
  resources :activities
  resources :donors
end

app/models/donor.rb
class Donor
  include Mongoid::Document

  field :name, type: String
  field :email, type: String
  field :phone, type: String
  field :address, type: String
  field :identify, type: String
  field :wordsto, type: String

  validates :name, presence: true
  validates :phone, presence: true
  # validates :identify, presence: true

  has_many :donored_books, class_name: 'Book'
end

app/controllers/admin/donors_controller.rb
class Admin::DonorsController < Admin::ApplicationController
  before_action :set_donor, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  # GET /donors
  # GET /donors.json
  def index
    # @donors = Donor.all
    @donors = Donor.page(params[:page]).per(10)
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
  end

  # GET /donors/new
  def new
    @donor = Donor.new
  end

  # GET /donors/1/edit
  def edit
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(donor_params)

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render :show, status: :created, location: @donor }
      else
        format.html { render :new }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donors/1
  # PATCH/PUT /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_url, notice: 'Donor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donor_params
      params.require(:donor).permit(:name, 
                                   :email, 
                                   :phone, 
                                   :address,
                                   :wordsto,
                                   :identify)
    end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: [:show, :edit, :update, :destroy]

  # GET /donors
  # GET /donors.json
  def index
    # @donors = Donor.all
    @donors = Donor.page(params[:page]).per(1)
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
  end

  # GET /donors/new
  def new
    @donor = Donor.new
  end

  # GET /donors/1/edit
  def edit
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(donor_params)

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render :show, status: :created, location: @donor }
      else
        format.html { render :new }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    q = params['q']
    res = Net::HTTP.get(URI.parse(URI.escape("https://api.douban.com/v2/book/search?q=#{q}&fields=id,title,image,summary")))
    @json_info = JSON::parse(res)

    # respond_to do |format|
    #   # format.json { render :show, status: :created, location: @donor }
    # end
  end

  def donor
    book_id = params['book_id']
    res = Net::HTTP.get(URI.parse(URI.escape("https://api.douban.com/v2/book/#{book_id}")))
    @json_info = JSON::parse(res)
  end

  # PATCH/PUT /donors/1
  # PATCH/PUT /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_url, notice: 'Donor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donor_params
      params.require(:donor).permit(:name, 
                                   :email, 
                                   :phone,
                                   :wordsto)
    end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/admin/donors/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <i class="fa fa-users"></i> 捐赠者列表
    </h1>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-users"></i> 用户管理
      </li>
      <li class="active">
          <i class="fa fa-user"></i> 捐赠者列表
      </li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>姓名</th>
            <th>邮箱</th>
            <th>电话</th>
            <th>地址</th>
            <th>身份</th>
            <th>寄语</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @donors.each do |donor| %>
          <tr>
              <td><%= link_to(donor.name, admin_donor_path(donor)) %></td>
              <td><%= donor.email%></td>
              <td><%= donor.phone %></td>
              <td><%= donor.address %></td>
              <td>
                <%= donor.identify %>
              </td>
              <td>
                <%= donor.wordsto %>
              </td>
              <td><%= link_to '查看', admin_donor_path(donor) , :class => 'btn btn-success btn-sm'%> &nbsp;
                  <%= link_to '编辑', edit_admin_donor_path(donor), :class => 'btn btn-primary btn-sm' %> &nbsp;
                  <%= link_to '删除', admin_donor_path(donor), method: :delete, data: { confirm: '确认删除？' }, :class=>'btn btn-danger btn-sm'%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= paginate @donors, :outer_window => 2 %>

<%= link_to 'New Donor', new_admin_donor_path %>

app/views/admin/donors/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <i class="fa fa-users"></i> 新增捐赠者
    </h1>
    <ol class="breadcrumb">
      <li>
        <i class="fa fa-users"></i> 新增捐赠者
      </li>
      <li class="active">
          <i class="fa fa-user"></i> 新增捐赠者
      </li>
    </ol>
  </div>
</div>

<%= render 'form' %>